# Generated by Django 5.1.5 on 2025-01-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'table_number',
                    models.IntegerField(
                        help_text='Номер стола', verbose_name='Номер стола'
                    ),
                ),
                ('items', models.JSONField(verbose_name='Блюда')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('waiting', 'В ожидании'),
                            ('ready', 'Готово'),
                            ('paid', 'Оплачено'),
                        ],
                        default='waiting',
                        max_length=25,
                        verbose_name='Status',
                    ),
                ),
                (
                    'total_price',
                    models.IntegerField(verbose_name='Стоимость заказа'),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
